name: "my hello action"

description: "say hello with GitHub Actions"

inputs:
  greeting:
    description: "what is the greeting message"
    required: true
    default: "Hello World!"
    
runs:
  using: "node12"
  main: "main.js"
